[package]
name = "nbd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = { version = "2.0.0-alpha", features = ["serde"] }
byteorder = "1.4.3"
serde = { version = "1.0.130", features = ["derive"] }
