name: Rust

on:
  push:
    branches: [ master ]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: add musl target
      run: rustup target add x86_64-unknown-linux-musl
    - name: Install qemu-utils
      run: sudo apt-get install -y qemu-utils
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
